### ISSUE TITLE
Unable to Download

### ISSUE THREAD

**Issue by ka-ross** [bhimebau/nucleo_f303re#4]
We were unable to download, as the st-flash.log says "Couldn't find any ST-Link/V2 devices".

-Billie and Kyle

**Comment by bhimebau** [comment]
Guys,

I am suspicious that you may be pulling the old st-utils. Type the 
following:

which st-util

This should say /l/arm2/devtools/bin. However, I suspect that yours 
still points to the old codesourcery tools. I had to update the st-utils 
to the latest version to get support for the V2-1 st-link. I only 
updated the /l/arm2/devtools/bin.

Bryce

**Comment by ka-ross** [comment]
Bryce,

This is most certainly the issue. we're still pulling from the codesourcery tools. I am looking it up, but I cannot find how to update to point at the V2-1 st-link, could you point me in the right direction?

**Comment by bhimebau** [comment]
Take a look at this link on how to setup your path to point at the correct tools.

https://github.iu.edu/SOIC-Computer-Structures/Fall-2015/wiki/Lab4#25-path

By the way, I have the board here if you would like to grab it to work with the accel. I have a meeting at 11:30 but the board will be on my bench right under the microscope.

Bryce

**Comment by ka-ross** [comment]
I got the board to download, but I can't seem to get screen running. I noticed that the bitrate is 38400, but running screen /dev/ttyACM0 at that baud rate isn't producing any results. At this point Billie and I are convinced its a simplistic solution that we're missing.

**Comment by bhimebau** [comment]
Are you in the lab right now?

Bryce

**Comment by ka-ross** [comment]
Yes

**Comment by bhimebau** [comment]
Be down in a minute.

Bryce
